Pull request
KumaHoon/OSDA-bot pull request #10
Opened 2020-12-18 18:36 UTC by leewontae0

Add test/bot.py

2020-12-18 18:44 UTC, aelrot12 commented
1. Pull request 라는 이름 대신 무엇이 변경되었는지 알 수 있게 PR 제목을 Add bot.py로 수정하시는게 좋을 것 같습니다.
2.  test용이더라도 이미 py 파일 이름이 test기 때문에 feature/ 폴더에 작성해서 PR해주시는 게 좋을 것 같습니다.

2020-12-19 02:31 UTC, KumaHoon requested changes
1. 리스트 길이 제한
2. 레포에 dice.py처럼 한국어 기능도 추가해주시면 좋을 것 같습니다!

2020-12-19 02:31 UTC, KumaHoon commented on test/bot.py
> +    await ctx.send(', '.join(dice))
dice 굴리는 횟수가 너무 많으면 메모리 문제가 생길 것 같습니다.. 대략적으로 제한하는 방향이 좋은 것 같습니다!

2020-12-19 05:41 UTC, leewontae0 commented
> 1. Pull request 라는 이름 대신 무엇이 변경되었는지 알 수 있게 PR 제목을 Add bot.py로 수정하시는게 좋을 것 같습니다.
> 2. test용이더라도 이미 py 파일 이름이 test기 때문에 feature/ 폴더에 작성해서 PR해주시는 게 좋을 것 같습니다.
> 3. 내용의 경우 **Add** bot.py 처럼 핵심 내용에 강조 표시를 해 주시면 더 보기 깔끔할 것 같습니다.

2020-12-19 06:17 UTC, leewontae0 commented on test/bot.py
> +    await ctx.send(', '.join(dice))
좋은 커멘트 감사합니다 :)
리스트 길이 제한 이라고 말씀하신 것이 잘 이해가 되지 않습니다.
혹시 이 말씀이 어떤 것을 의미하시는 지 상세히 설명 가능하실까요? ㅎㅎ

2020-12-19 06:17 UTC, leewontae0 commented
> 1. Pull request 라는 이름 대신 무엇이 변경되었는지 알 수 있게 PR 제목을 Add bot.py로 수정하시는게 좋을 것 같습니다.
> 2. test용이더라도 이미 py 파일 이름이 test기 때문에 feature/ 폴더에 작성해서 PR해주시는 게 좋을 것 같습니다.
> 3. 내용의 경우 **Add** bot.py 처럼 핵심 내용에 강조 표시를 해 주시면 더 보기 깔끔할 것 같습니다.

2020-12-19 06:18 UTC, leewontae0 commented
> 1. Pull request 라는 이름 대신 무엇이 변경되었는지 알 수 있게 PR 제목을 Add bot.py로 수정하시는게 좋을 것 같습니다.
> 2. test용이더라도 이미 py 파일 이름이 test기 때문에 feature/ 폴더에 작성해서 PR해주시는 게 좋을 것 같습니다.
> 3. 내용의 경우 **Add** bot.py 처럼 핵심 내용에 강조 표시를 해 주시면 더 보기 깔끔할 것 같습니다.

2020-12-19 06:28 UTC, KumaHoon commented on test/bot.py
> +    await ctx.send(', '.join(dice))
41번 줄에 dice = [ str(random.choice(range(1, number_of_sides + 1)))
        for _ in range(number_of_dice)]로 되어있는데 여기 안에 있는 리스트의 요소 갯수(number_of_dice) 제한해주셔야 될 것 같아요..

2020-12-19 11:23 UTC, leewontae0 commented on test/bot.py
> +    await ctx.send(', '.join(dice))
리스트 길이 제한과 dice 굴리는 횟수를 제한하는 것을 요구하셔서 두 개의 요구가 다른 의미인줄 알았습니다 ㅎㅎ; 
추가해서 PR하겠습니다.

2020-12-19 11:33 UTC, leewontae0 commented
> 1. 리스트 길이 제한
> 2. 레포에 dice.py처럼 한국어 기능도 추가해주시면 좋을 것 같습니다!

2020-12-19 11:33 UTC, closed without merging